#cloud-config
# vim: syntax=yaml

repo_update: true

packages:
- python3
- python3-pip
- openssh-client

write_files:
- path: /etc/ssh/sshd_config
  owner: root:root
  content: |
    UseDNS no
    ClientAliveInterval 340
    Subsystem sftp /usr/lib/openssh/sftp-server
    AcceptEnv LANG LC_*
    UsePAM yes
    PubkeyAuthentication yes
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    AllowTcpForwarding yes
    AllowAgentForwarding yes
    PermitTTY yes
    PermitTunnel yes

runcmd:
- systemctl restart sshd

output:
  output: { all: "| tee -a /var/log/cloud-init-output.log" }

final_message: "The system is up, after $UPTIME seconds"
